In [1]:
using Revise

In [2]:
push!(LOAD_PATH, "/home/amir/work/QSpin/src/")

using LinearAlgebra
using SparseArrays
using QSpin

In [3]:
⊗ = kron

zup = QSpin.SpinState([2], sparse([1., 0.]))
zdn = QSpin.SpinState([2], sparse([0., 1.]))
s0 = (zup ⊗ zdn - zdn ⊗ zup)

wp = 1/sqrt(3) * (zdn ⊗ zup ⊗ zup + zup ⊗ zdn ⊗ zup + zup ⊗ zup ⊗ zdn)
wm = 1/sqrt(3) * (zup ⊗ zdn ⊗ zdn + zdn ⊗ zup ⊗ zdn + zdn ⊗ zdn ⊗ zup)

SpinState{Float64}([2, 2, 2],   [4]  =  0.57735
  [6]  =  0.57735
  [7]  =  0.57735)

In [4]:
# AKLT construction
s0 = (zup ⊗ zdn - zdn ⊗ zup)
s = s0 ⊗ s0 ⊗ s0 ⊗ s0 ⊗ s0

p1 = reshape([1,0,0] ⊗ [1,0,0,0] + 1/sqrt(2) * ( [0,1,0] ⊗ [0,1,1,0]) + [0,0,1] ⊗ [0,0,0,1],4,3)'
p = I(2) ⊗ p1 ⊗ p1 ⊗ p1 ⊗ p1 ⊗ I(2)
s2 = QSpin.SpinState([2,3,3,3,3,2], sparse(p * s.vals))
#s2.vals
QSpin.sshow(s2)
svd(Matrix(reshape(normalize(s2.vals),18,18))).S[1:6]
#QSpin.sshow(s)
#tenp = QSpin.tensorprod
#tenp(zup, zdn) + tenp(zdn, zup)

↓⇔⇔⇔⇔↑:   0.24999999999999992
↓⇔⇔⇔⇑↓:   -0.3535533905932737
↓⇔⇔⇑⇓↑:   -0.4999999999999999
↓⇔⇔⇑⇔↓:   0.3535533905932737
↓⇔⇑⇓⇔↑:   -0.4999999999999999
↓⇔⇑⇓⇑↓:   0.7071067811865475
↓⇔⇑⇔⇓↑:   0.4999999999999999
↓⇔⇑⇔⇔↓:   -0.3535533905932737
↓⇑⇓⇔⇔↑:   -0.4999999999999999
↓⇑⇓⇔⇑↓:   0.7071067811865475
↓⇑⇓⇑⇓↑:   1.0
↓⇑⇓⇑⇔↓:   -0.7071067811865475
↓⇑⇔⇓⇔↑:   0.4999999999999999
↓⇑⇔⇓⇑↓:   -0.7071067811865475
↓⇑⇔⇔⇓↑:   -0.4999999999999999
↓⇑⇔⇔⇔↓:   0.3535533905932737
↑⇓⇔⇔⇔↑:   -0.3535533905932737
↑⇓⇔⇔⇑↓:   0.4999999999999999
↑⇓⇔⇑⇓↑:   0.7071067811865475
↑⇓⇔⇑⇔↓:   -0.4999999999999999
↑⇓⇑⇓⇔↑:   0.7071067811865475
↑⇓⇑⇓⇑↓:   -1.0
↑⇓⇑⇔⇓↑:   -0.7071067811865475
↑⇓⇑⇔⇔↓:   0.4999999999999999
↑⇔⇓⇔⇔↑:   0.3535533905932737
↑⇔⇓⇔⇑↓:   -0.4999999999999999
↑⇔⇓⇑⇓↑:   -0.7071067811865475
↑⇔⇓⇑⇔↓:   0.4999999999999999
↑⇔⇔⇓⇔↑:   -0.3535533905932737
↑⇔⇔⇓⇑↓:   0.4999999999999999
↑⇔⇔⇔⇓↑:   0.3535533905932737
↑⇔⇔⇔⇔↓:   -0.24999999999999992



6-element Array{Float64,1}:
 0.7071067811865477    
 0.7071067811865474    
 6.14216276975471e-17  
 3.7438090068962396e-17
 1.6201456940065642e-17
 1.1346296772743332e-17

In [5]:
s = s0 ⊗ s0 ⊗ s0 
sss = QSpin.permutespins(s, [2,3,4,5,6,1])
p1 = reshape([1,0,0] ⊗ [1,0,0,0] + 1/sqrt(2) * ( [0,1,0] ⊗ [0,1,1,0]) + [0,0,1] ⊗ [0,0,0,1],4,3)'
p = (p1 ⊗ p1 ⊗ p1)
s2 = QSpin.SpinState([3,3,3], sparse(p * sss.vals))
QSpin.sshow(s2)
svd(Matrix(reshape(normalize(s2.vals),3,9))).S
#sss.vals
#s.vals
#s2.vals

⇓⇔⇑:   -0.7071067811865475
⇓⇑⇔:   0.7071067811865475
⇔⇓⇑:   0.7071067811865475
⇔⇑⇓:   -0.7071067811865475
⇑⇓⇔:   -0.7071067811865475
⇑⇔⇓:   0.7071067811865475



3-element Array{Float64,1}:
 0.5773502691896258
 0.5773502691896257
 0.5773502691896257

In [6]:
QSpin.conf2index(s2, [1,1,1])

14

In [7]:
s = s0 ⊗ s0 ⊗ s0 ⊗ s0 ⊗ s0 ⊗ s0 ⊗ s0
sss = QSpin.permutespins(s, [2,3,4,5,6,7,8,9,10,11,12,13,14,1])
p1 = reshape([1,0,0] ⊗ [1,0,0,0] + 1/sqrt(2) * ( [0,1,0] ⊗ [0,1,1,0]) + [0,0,1] ⊗ [0,0,0,1],4,3)'
p = (p1 ⊗ p1 ⊗ p1 ⊗ p1 ⊗ p1 ⊗ p1 ⊗ p1)
s2 = QSpin.SpinState([3,3,3,3,3,3,3], sparse(p * sss.vals));
#QSpin.sshow(s2)

In [8]:
uniform = sparsevec(s2.vals.nzind, ones(length(s2.vals.nzind)), 27*81)
A = Matrix(reshape(normalize(uniform),27,81))
#A = Matrix(reshape(normalize(s2.vals),27,81))
svd(A).S[1:6]

6-element Array{Float64,1}:
 0.5551856605011776    
 0.5039526306789696    
 0.5039526306789696    
 0.4082482904638629    
 0.13101796735828425   
 1.0342839418821266e-16

In [9]:
state = wm ⊗ wp ⊗ wm ⊗ wp ⊗ wm ⊗ wp
#QSpin.sshow(state)
#Making the projection operators
p1  = sparse(reshape([1,0,0,0] ⊗ [1,0,0] +  1/sqrt(2) * ([0,1,1,0] ⊗ [0,1,0]) +  [0,0,0,1] ⊗ [0,0,1], 3,4))
#display(p1)
p32 = sparse(reshape(
    [1,0,0,0,0,0,0,0] ⊗ [1,0,0,0] + 
    1/sqrt(3) * [0,1,1,0,1,0,0,0] ⊗ [0,1,0,0] +
    1/sqrt(3) * [0,0,0,1,0,1,1,0] ⊗ [0,0,1,0] +
    [0,0,0,0,0,0,0,1] ⊗ [0,0,0,1],
    4,8
))
#display(p32)
p = I(2) ⊗ p1 ⊗ p32 ⊗ p32 ⊗ p32 ⊗ p32 ⊗ p1 ⊗ I(2)
perm12 = [1,2,4,3,5,7,6,8,10,9,11,12]
perm18 = [1,2,4,3,5,7,6,8,10,9,11,13,12,14,16,15,17,18]
state_perm = QSpin.permutespins(state, perm18)
awesome = QSpin.SpinState([2,3,4,4,4,4,3,2], sparse(p * state_perm.vals))

#QSpin.sshow(awesome)

SpinState{Float64}([2, 3, 4, 4, 4, 4, 3, 2],   [2152]  =  0.00205761
  [2153]  =  0.0029099
  [2157]  =  0.00356389
  [2170]  =  0.00411523
  [2171]  =  0.00581981
  [2174]  =  0.0029099
  [2175]  =  0.00617284
  [2179]  =  0.0050401
  [2188]  =  0.00617284
  [2189]  =  0.00872971
          ⋮
  [8216]  =  0.00823045
  [8217]  =  0.0116396
  [8221]  =  0.00823045
  [8266]  =  0.0050401
  [8267]  =  0.00712778
  [8271]  =  0.0050401
  [8284]  =  0.0050401
  [8285]  =  0.00712778
  [8288]  =  0.00411523
  [8289]  =  0.00581981
  [8293]  =  0.00411523)

In [10]:
svd(Matrix(reshape(normalize(awesome.vals),2*3*4*4,2*3*4*4))).S[1:6]

6-element Array{Float64,1}:
 0.7761619052021769   
 0.5655206394453202   
 0.26172901454492015  
 0.0962134409509804   
 8.661773670385177e-17
 7.509823837439474e-17